apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
type: Opaque
data:
  activemq-password: {{ .Values.auth.password | b64enc | quote }}